export const projectsData = [
  {
    title:
      'Skynora — многостраничное веб-приложение для телеграм бота по северному сиянию',
    link: 'https://skynora.ru',
    imageSrc: 'img/portfolio/min/skynora-site.png',
    alt: 'Многостраничный сайт Skynora с информацией о северном сиянии и продвижением Telegram-бота для регионов России',
    categories: ['product', 'astro', 'frontend'],
  },
  {
    title: 'Skynora Bot — Telegram-бот для уведомлений о северном сиянии',
    link: 'https://t.me/skynora_bot',
    imageSrc: 'img/portfolio/min/skynora-bot.png',
    alt: 'Telegram-бот Skynora для уведомлений о северном сиянии по наблюдениям пользователей и данным NOAA',
    categories: ['bot', 'telegram', 'backend'],
  },
  {
    title: 'FullStack-разработка социальной сети Zling',
    link: 'https://zling.vercel.app',
    imageSrc: 'img/portfolio/min/zling.jpeg',
    alt: `Социальная сеть Zling с полным стеком разработки: интерфейс, серверная часть и взаимодействие между ними.
    
Данные для демо входа в аккаунт: 
 - email: zling.krbln@gmail.com
 - pass: test_pasS1$
    `,
    githubLink: 'https://github.com/Leonid-Korobkov/social-net-front',
    githubLinkBack: 'https://github.com/Leonid-Korobkov/social-net-back',
    testAccount: {
      email: 'zling.krbln@gmail.com',
      password: 'test_pasS1$',
    },
    categories: ['fullstack', 'social', 'frontend', 'backend'],
  },
  {
    title: 'Веб-приложение для заметок (KRB Notes)',
    link: 'https://krb-notes.vercel.app/',
    imageSrc: 'img/portfolio/min/krb-notes.jpg',
    alt: 'Веб-приложение KRB Notes для создания и управления заметками',
    githubLink: 'https://github.com/Leonid-Korobkov/KRB-Notes',
    categories: ['frontend', 'react', 'notes'],
  },
  {
    title: 'Перевод систем счисления (math-project)',
    link: 'https://leonid-korobkov.github.io/math-project/',
    imageSrc: 'img/portfolio/min/math-project.jpg',
    alt: 'Инструмент math-project для перевода чисел между разными системами счисления',
    githubLink: 'https://github.com/Leonid-Korobkov/math-project',
    categories: ['frontend', 'tools', 'vanilla-js'],
  },
  {
    title: 'Веб-приложение - пиццерия (TypeScript, React, RTK, mock API)',
    link: 'https://react-food-delivery-one.vercel.app',
    imageSrc: 'img/portfolio/min/react-food-delivery.jpg',
    alt: 'Интернет-пиццерия на TypeScript и React с корзиной, каталогом и mock API',
    githubLink: 'https://github.com/Leonid-Korobkov/react-food-delivery',
    categories: ['frontend', 'react', 'typescript'],
  },
  {
    title:
      'Верстка сайта под Wordpress с посадкой. НОЭКС - Строительная компания',
    link: 'http://o92141m5.beget.tech/noex/',
    imageSrc: 'img/portfolio/min/noex.jpg',
    alt: 'Лендинг строительной компании НОЭКС, сверстанный для WordPress c дальнейшей интеграцией в CMS',
    githubLink: 'https://github.com/Leonid-Korobkov/noex',
    categories: ['frontend', 'wordpress', 'business'],
  },
  {
    title: 'Real-time Chat. React, Firebase, MUI',
    link: 'https://chat-react-krbln.vercel.app/',
    imageSrc: 'img/portfolio/min/realtime-chat.jpg',
    alt: 'Чат в реальном времени на React, Firebase и Material UI',
    githubLink: 'https://github.com/Leonid-Korobkov/chat',
    categories: ['frontend', 'react', 'firebase'],
  },
  {
    title: 'Шахматы на React, TypeScript, PostCSS, Vite',
    link: 'https://react-chess-one.vercel.app',
    imageSrc: 'img/portfolio/min/react-chess.png',
    alt: 'Интерактивная шахматная игра на React и TypeScript',
    githubLink: 'https://github.com/Leonid-Korobkov/react-chess',
    categories: ['frontend', 'game', 'react', 'typescript'],
  },
  {
    title: 'Мини-клон Excel. HTML, CSS, JS.',
    link: 'https://excel-krbln.web.app/',
    imageSrc: 'img/portfolio/min/excel.jpg',
    alt: 'Мини-клон Excel для работы с таблицами в браузере на HTML, CSS и JavaScript',
    githubLink: 'https://github.com/Leonid-Korobkov/excel',
    categories: ['tools', 'vanilla-js', 'game'],
  },
  {
    title: 'Викторина по истории (quiz-history)',
    link: 'https://leonid-korobkov.github.io/quiz-history/',
    imageSrc: 'img/portfolio/min/quiz-history.png',
    alt: 'Викторина по истории с вопросами и интерактивной проверкой ответов',
    githubLink: 'https://github.com/Leonid-Korobkov/quiz-history',
    categories: ['frontend', 'vanila-js'],
  },
  {
    title: 'Простое веб-приложение для заметок (simple-notes)',
    link: 'https://simple-notes-react.vercel.app/',
    imageSrc: 'img/portfolio/min/simple-notes.png',
    alt: 'Простое веб-приложение Simple Notes для быстрых заметок на React',
    githubLink: 'https://github.com/Leonid-Korobkov/simple-notes-react',
    categories: ['frontend', 'react', 'notes'],
  },
  {
    title: 'Таймер для медитации. HTML, CSS, JS.',
    link: 'https://leonid-korobkov.github.io/timer-meditation/',
    imageSrc: 'img/portfolio/min/timer-meditation.jpg',
    alt: 'Таймер для медитации с настройкой времени и простым управлением в браузере',
    githubLink: 'https://github.com/Leonid-Korobkov/timer-meditation',
    categories: ['frontend', 'vanilla-js', 'tools'],
  },
  {
    title: 'Верстка интернет-магазина. GoldFish',
    link: 'http://o92141m5.beget.tech/goldFish/',
    imageSrc: 'img/portfolio/min/goldfish.jpg',
    alt: 'Интернет-магазин GoldFish, сверстанный в формате лендинга для продажи товаров',
    githubLink: 'https://github.com/Leonid-Korobkov/GoldFish',
    categories: ['landing', 'ecommerce'],
  },
  {
    title: 'Верстка лендинга с посадкой на wordpress. Furniture shop',
    link: 'http://o92141m5.beget.tech/FurnitureShop/',
    imageSrc: 'img/portfolio/min/furniture-shop.jpg',
    alt: 'Лендинг мебельного магазина Furniture Shop с посадкой на WordPress',
    githubLink: 'https://github.com/Leonid-Korobkov/Furniture-shop',
    categories: ['landing', 'wordpress', 'ecommerce'],
  },
  {
    title: 'Мини-конструктор сайтов на JS',
    link: 'https://site-builder-krbln.web.app',
    imageSrc: 'img/portfolio/min/site-builder.jpg',
    alt: 'Мини-конструктор сайтов на JavaScript для сборки и редактирования страниц',
    githubLink: 'https://github.com/Leonid-Korobkov/site-builder',
    categories: ['tools', 'game', 'vanilla-js'],
  },
  {
    title: 'Приложение «Задай мне вопрос» на JavaScript + MUI + Firebase',
    link: 'https://podcast-krbln.web.app',
    imageSrc: 'img/portfolio/min/question.jpg',
    alt: 'Приложение «Задай мне вопрос» на JavaScript, MUI и Firebase',
    githubLink: 'https://github.com/Leonid-Korobkov/podcast-krbln',
    categories: ['game', 'firebase', 'tools'],
  },
  {
    title: 'Плагин на JavaScript. Загрузка изображений на сервер Firebase',
    link: 'https://plugin-upload-krbln.web.app/',
    imageSrc: 'img/portfolio/min/plugin-upload.jpg',
    alt: 'JavaScript-плагин для загрузки изображений на сервер Firebase',
    categories: ['tools', 'game', 'firebase'],
  },
  {
    title: 'Отскакивающие мячики (bounceBalls)',
    link: 'https://leonid-korobkov.github.io/bounceBalls/',
    imageSrc: 'img/portfolio/min/bounce-balls.jpg',
    alt: 'Canvas-игра с отскакивающими мячиками и динамической физикой движения',
    githubLink: 'https://github.com/Leonid-Korobkov/bounceBalls',
    categories: ['game', 'canvas'],
  },
  {
    title: 'Генератор цветов (RandomColors)',
    link: 'https://leonid-korobkov.github.io/RandomColors/',
    imageSrc: 'img/portfolio/min/random-color.jpg',
    alt: 'Генератор случайных цветов с выводом готовых цветовых значений',
    githubLink: 'https://github.com/Leonid-Korobkov/RandomColors',
    categories: ['tools', 'game'],
  },
  {
    title: 'Игра "Змейка"(SnakeGame)',
    link: 'https://leonid-korobkov.github.io/game-snake/',
    imageSrc: 'img/portfolio/min/snake.jpg',
    alt: 'Классическая игра "Змейка" в браузере',
    githubLink: 'https://github.com/Leonid-Korobkov/game-snake',
    categories: ['game', 'vanila-js'],
  },
  {
    title: 'Игра "Виселица"(hangman-game)',
    link: 'https://leonid-korobkov.github.io/hangman-game/',
    imageSrc: 'img/portfolio/min/hangman.jpg',
    alt: 'Браузерная игра "Виселица" с угадыванием слова',
    githubLink: 'https://github.com/Leonid-Korobkov/hangman-game',
    categories: ['game', 'vanila-js', 'book'],
  },
  {
    title: 'Игра на прицеливание (aim-game)',
    link: 'https://leonid-korobkov.github.io/aim-game/',
    imageSrc: 'img/portfolio/min/aim-game.jpg',
    alt: 'Игра на прицеливание с проверкой скорости реакции и точности',
    githubLink: 'https://github.com/Leonid-Korobkov/aim-game',
    categories: ['game', 'vanila-js'],
  },
  {
    title: 'Мини-клон Trello. HTML, CSS, JS.',
    link: 'https://leonid-korobkov.github.io/Drag-n-Drop/',
    imageSrc: 'img/portfolio/min/drag-drop.jpg',
    alt: 'Мини-клон Trello для работы с задачами и drag-and-drop карточками',
    githubLink: 'https://github.com/Leonid-Korobkov/Drag-n-Drop',
    categories: ['tools', 'vanila-js', 'game'],
  },
  {
    title: 'Доска для рисования (board)',
    link: 'https://leonid-korobkov.github.io/board/',
    imageSrc: 'img/portfolio/min/board.jpg',
    alt: 'Доска для рисования в браузере с инструментами для свободного скетчинга',
    githubLink: 'https://github.com/Leonid-Korobkov/board',
    categories: ['tools', 'game'],
  },
  {
    title: 'Слайдер (slider)',
    link: 'https://leonid-korobkov.github.io/slider/',
    imageSrc: 'img/portfolio/min/slider.jpg',
    alt: 'UI-компонент слайдера для перелистывания контента',
    githubLink: 'https://github.com/Leonid-Korobkov/slider',
    categories: ['components', 'game'],
  },
  {
    title: 'Карточки (cards)',
    link: 'https://leonid-korobkov.github.io/cards/',
    imageSrc: 'img/portfolio/min/cards.jpg',
    alt: 'Набор карточек для демонстрации контента в интерфейсе',
    githubLink: 'https://github.com/Leonid-Korobkov/cards',
    categories: ['components', 'game'],
  },
  {
    title: 'Верстка сайта productivity',
    link: 'https://leonid-korobkov.github.io/productivity/',
    imageSrc: 'img/portfolio/min/productivity.jpg',
    alt: 'Лендинг Productivity с адаптивной версткой',
    githubLink: 'https://github.com/Leonid-Korobkov/productivity',
    categories: ['landing', 'frontend'],
  },
  {
    title: 'Верстка сайта Mitravel',
    link: 'https://leonid-korobkov.github.io/Mitravel/',
    imageSrc: 'img/portfolio/min/mitravel.jpg',
    alt: 'Лендинг Mitravel с адаптивной версткой туристического сайта',
    githubLink: 'https://github.com/Leonid-Korobkov/Mitravel',
    categories: ['landing', 'frontend'],
  },
  {
    title: 'Верстка сайта ActiveBox',
    link: 'https://leonid-korobkov.github.io/ActiveBox/',
    imageSrc: 'img/portfolio/min/activebox.jpg',
    alt: 'Лендинг ActiveBox с адаптивной версткой промо-страницы',
    githubLink: 'https://github.com/Leonid-Korobkov/ActiveBox',
    categories: ['landing', 'frontend'],
  },
]
